
global:
  slack_api_url: 'https://hooks.slack.com/services/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'

  route:
    receiver: 'slack-notifications'

  receivers:
    - name: 'slack-notifications'
  slack_configs:
    - channel: '#georgsold' 
