version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_V}
    ports:
      - ${PORT_NUM}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_V}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_V}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge
